png("plot4.png")
par(mfrow=c(2,2))
plot(sub$time, sub$Global_active_power, type="l",ylab="Global Active Power", xlab="")
plot(sub$time, sub$Voltage, type="l", ylab="Voltage", xlab="datatime")
plot(sub$time, sub$Sub_metering_1, type="l",ylab="Energy sub metering", xlab="")
lines(sub$time, sub$Sub_metering_2, col="red")
lines(sub$time, sub$Sub_metering_3, col="blue")
legend("topright", lty=1, legend=c(paste("sub_metering_",1:3)), col=c("black","red","blue"),cex=0.5)
plot(sub$time, sub$Global_reactive_power, type="l", ylab="Global_ractive_power", xlab="datatime")
dev.off()